# Generated by Django 6.0.5 on 2026-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studio',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='studio_profile_pictures/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='studio_wallpapers/'),
        ),
    ]
