# Generated by Django 6.0.5 on 2026-06-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_seed_catalog_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='profile_picture',
        ),
    ]
