# Generated by Django 6.0.5 on 2026-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_studio_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='logo',
            field=models.ImageField(default='defaults/default_logo.png', upload_to='studio_logos/'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='wallpaper',
            field=models.ImageField(blank=True, default='defaults/default_wallpaper.svg', null=True, upload_to='studio_wallpapers/'),
        ),
    ]
